name: PublishCI

on:
  push:
    branches: [ ci-test ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Install parcel
        run: npm install -g parcel-bundler

      - name: Build
        run: parcel build index.ts

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}